const MAXIMUM_ATTEMPTS = 60;

const DEBUG_NAME_AMAZON = 'aa';
const DEBUG_NAME_ARCHAMBAULT = 'ar';
const DEBUG_NAME_LESLIBRAIRES = 'll';
const DEBUG_NAME_QUIALU = 'rc';
const DEBUG_NAME_WATTPAD = 'wp';

module.exports = {
  MAXIMUM_ATTEMPTS,
  DEBUG_NAME_AMAZON,
  DEBUG_NAME_ARCHAMBAULT,
  DEBUG_NAME_LESLIBRAIRES,
  DEBUG_NAME_QUIALU,
  DEBUG_NAME_WATTPAD,
};
